/*
**
** File: cf_external_functions.h
** This file is automatically generated by the
** chain flow assembler
**
*/

#ifndef _EXTERNAL_FUNCTIONS_H_
#define _EXTERNAL_FUNCTIONS_H_ 

#include "cf_chain_flow_support.h" 
#include "cf_events.h"
/*
This is the symbolic definitions of the chains
*/



#define  heart_beat   0



int pat_watch_dog(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int  toggle_heart_beat(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);






#endif
